### ISSUE TITLE
类型转换失败

### ISSUE THREAD

**Issue by SXZXD** [Tecode/flutter_book#2]
你好启动应用，会报错，这些类型转换失败！
The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'
The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

**Comment by Tecode** [comment]
@SXZXD 修改`pubspec.yaml`文件里面的`flutter_svg`依赖`flutter_svg: ">=0.12.4"`修改为`flutter_svg: ">=0.13.0"`

**Comment by SXZXD** [comment]
是因为svg版本问题，我已经换了！
The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'
photo_view  也出现同样错误类型无法转换

**Comment by Tecode** [comment]
@SXZXD `photo_view`你也换一下版本，有可能是我们`Flutter`版本不一样导致了依赖文件的版本也不一样

**Comment by SXZXD** [comment]
flutter跟photo_view我都用的是最新版。

**Comment by SXZXD** [comment]
photo_view 已进行修正，还没有发布版本

**Comment by Tecode** [comment]
我现在的`Flutter`版本是1.5.9,如果遇到了依赖版本问题请修改一下你的版本
```bash
Flutter 1.5.9-pre.223 • channel master • https://github.com/flutter/flutter.git
Framework • revision b76a1e8312 (11 days ago) • 2019-05-13 09:06:30 +0100
Engine • revision 816d3fc586
Tools • Dart 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)
```

**Comment by JimmyLee05** [comment]
在Flutter的文件夹的，git checkout v1.5.9 没有这个version的Flutter

**Comment by Tecode** [comment]
@SXZXD 升级一下flutter的版本，现在是最新的1.7.8+hotfix.3，然后拉一下代码，我把依赖都改到最新了。
