### ISSUE TITLE
this is the best app I've seen to learn flutter, so far

### ISSUE THREAD

**Issue by CavalcanteLeo** [Tecode/flutter_book#3]
But I don't speak Chinese, could any chinese translate this repo to english? 
This would help me and a lot other developers too

Thank you a lot for this code.

**Comment by Tecode** [comment]
Hi @CavalcanteLeo 

I’m busy now and I don’t have time to translate it into English. If you encounter problems, you can file an`issue`. I will answer it as soon as possible.

Finally, thank you for your support.
